export const exampleExamQuestions = [
  {
    category: "C++ Fundamentals",
    question: "What is the correct way to declare a variable in C++?",
    options: ["int x;", "x: int;", "declare x as int", "int: x;"],
    code: "",
    correctAnswer: "int x;",
  },
  {
    category: "C++ Fundamentals",
    question: "Which of the following is NOT a primitive data type?",
    options: ["int", "float", "bool", "string"],
    code: "",
    correctAnswer: "string",
  },
  {
    category: "C++ Fundamentals",
    question: "What does the 'auto' keyword do in modern C++?",
    options: ["Declares automatic variables", "Enables automatic type deduction", "Makes variables global", "Disables optimization"],
    code: "",
    correctAnswer: "Enables automatic type deduction",
  },
  {
    category: "C++ Fundamentals",
    question: "Which operator has the highest precedence?",
    options: ["*", "^", "()", "!"],
    code: "",
    correctAnswer: "()",
  },
  {
    category: "C++ Fundamentals",
    question: "What is the size of a pointer on a 64-bit system?",
    options: ["4 bytes", "8 bytes", "16 bytes", "Depends on architecture"],
    code: "",
    correctAnswer: "8 bytes",
  },
  {
    category: "Object-Oriented Programming",
    question: "What is the purpose of a constructor?",
    options: ["Construct objects and initialize members", "Create new objects", "Call parent methods", "Define static members"],
    code: "",
    correctAnswer: "Construct objects and initialize members",
  },
  {
    category: "Object-Oriented Programming",
    question: "Which access specifier is most restrictive?",
    options: ["public", "protected", "private", "internal"],
    code: "",
    correctAnswer: "private",
  },
  {
    category: "Object-Oriented Programming",
    question: "What is method overloading?",
    options: ["Using same method multiple times", "Same method name, different parameters", "Calling parent method", "Virtual methods"],
    code: "",
    correctAnswer: "Same method name, different parameters",
  },
  {
    category: "Object-Oriented Programming",
    question: "What is the this pointer?",
    options: ["Pointer to current class", "Pointer to current object", "Pointer to base class", "Null pointer"],
    code: "",
    correctAnswer: "Pointer to current object",
  },
  {
    category: "Object-Oriented Programming",
    question: "What is the purpose of an abstract class?",
    options: ["Define interface without implementation", "Speed up code", "Reduce memory usage", "Prevent instantiation"],
    code: "",
    correctAnswer: "Define interface without implementation",
  },
  {
    category: "Memory Management",
    question: "What does the & operator do in pointer context?",
    options: ["Bitwise AND", "Address-of operator", "Reference", "Dereference"],
    code: "",
    correctAnswer: "Address-of operator",
  },
  {
    category: "Memory Management",
    question: "What does the * operator do with pointers?",
    options: ["Multiplication", "Declare pointer", "Dereference pointer", "Both B and C"],
    code: "",
    correctAnswer: "Both B and C",
  },
  {
    category: "Memory Management",
    question: "What is nullptr in modern C++?",
    options: ["Same as NULL", "Newer way to represent null pointers", "Null string", "Not standard"],
    code: "",
    correctAnswer: "Newer way to represent null pointers",
  },
  {
    category: "Memory Management",
    question: "What is a memory leak?",
    options: ["Memory that overflows", "Allocated memory never freed", "Reading past array bounds", "Buffer overflow"],
    code: "",
    correctAnswer: "Allocated memory never freed",
  },
  {
    category: "Memory Management",
    question: "What does std::unique_ptr do?",
    options: ["Prevents copies", "Auto-deletes when out of scope", "Prevents null pointers", "Both A and B"],
    code: "",
    correctAnswer: "Both A and B",
  },
  {
    category: "STL Containers",
    question: "What does std::vector provide?",
    options: ["Dynamic array", "Matrix", "3D coordinates", "Mathematical vector"],
    code: "",
    correctAnswer: "Dynamic array",
  },
  {
    category: "STL Containers",
    question: "What is the time complexity of push_back on vector?",
    options: ["O(1) amortized", "O(n)", "O(log n)", "O(n log n)"],
    code: "",
    correctAnswer: "O(1) amortized",
  },
  {
    category: "STL Containers",
    question: "What does std::map use internally?",
    options: ["Hash table", "Binary search tree", "Array", "Linked list"],
    code: "",
    correctAnswer: "Binary search tree",
  },
  {
    category: "STL Containers",
    question: "What is the advantage of std::set over std::vector?",
    options: ["No duplicates, sorted", "Faster insertion", "Less memory", "Better for random access"],
    code: "",
    correctAnswer: "No duplicates, sorted",
  },
  {
    category: "STL Containers",
    question: "What does std::find return if element not found?",
    options: ["null", "Throws exception", "Iterator to end()", "-1"],
    code: "",
    correctAnswer: "Iterator to end()",
  },
  {
    category: "Exception Handling",
    question: "Which keyword throws an exception?",
    options: ["throw", "raise", "error", "catch"],
    code: "",
    correctAnswer: "throw",
  },
  {
    category: "Exception Handling",
    question: "Can you catch multiple exceptions?",
    options: ["No, only one", "Yes, with multiple catch blocks", "Only with polymorphism", "Not recommended"],
    code: "",
    correctAnswer: "Yes, with multiple catch blocks",
  },
  {
    category: "Exception Handling",
    question: "What is the base class for standard exceptions?",
    options: ["Exception", "std::exception", "Throwable", "Error"],
    code: "",
    correctAnswer: "std::exception",
  },
  {
    category: "Advanced Topics",
    question: "What are templates in C++?",
    options: ["HTML templates", "Generic programming", "Code templates", "Template files"],
    code: "",
    correctAnswer: "Generic programming",
  },
  {
    category: "Advanced Topics",
    question: "What is template specialization?",
    options: ["Specialized template", "Custom implementation for specific type", "Template inheritance", "Advanced template"],
    code: "",
    correctAnswer: "Custom implementation for specific type",
  },
  {
    category: "Advanced Topics",
    question: "Which header provides exception handling?",
    options: ["<error>", "<exception>", "<try>", "<catch>"],
    code: "",
    correctAnswer: "<exception>",
  },
  {
    category: "Advanced Topics",
    question: "How do you create threads in modern C++?",
    options: ["pthread_create", "CreateThread", "std::thread", "All of above"],
    code: "",
    correctAnswer: "std::thread",
  },
  {
    category: "Advanced Topics",
    question: "Which header for file operations?",
    options: ["<file>", "<fstream>", "<io>", "<stream>"],
    code: "",
    correctAnswer: "<fstream>",
  },
  {
    category: "Best Practices",
    question: "What does constexpr do?",
    options: ["Express constants", "Constant expression evaluable at compile time", "Const pointer", "Express constraints"],
    code: "",
    correctAnswer: "Constant expression evaluable at compile time",
  },
  {
    category: "Best Practices",
    question: "What is move semantics?",
    options: ["Moving objects", "Avoiding copies with rvalue references", "Pointer movement", "Memory movement"],
    code: "",
    correctAnswer: "Avoiding copies with rvalue references",
  },
  {
    category: "Best Practices",
    question: "What is an rvalue reference?",
    options: ["Right value reference", "Reference to temporary", "Forward reference", "Both B and C"],
    code: "",
    correctAnswer: "Both B and C",
  },
  {
    category: "Best Practices",
    question: "What is the Singleton pattern?",
    options: ["Single data member", "One instance of a class", "Single inheritance", "One constructor"],
    code: "",
    correctAnswer: "One instance of a class",
  },
  {
    category: "Best Practices",
    question: "What should const mean?",
    options: ["Variable name", "Constant value", "Compile-time constant", "All of the above"],
    code: "",
    correctAnswer: "All of the above",
  },
  {
    category: "STL Algorithms",
    question: "What is std::sort's average time complexity?",
    options: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"],
    code: "",
    correctAnswer: "O(n log n)",
  },
  {
    category: "STL Algorithms",
    question: "What is std::reverse used for?",
    options: ["Undo operation", "Reverse container order", "Opposite of sort", "Backward iteration"],
    code: "",
    correctAnswer: "Reverse container order",
  },
  {
    category: "STL Algorithms",
    question: "What is range-based for loop?",
    options: ["For loop with range", "for (auto x : container)", "Both A and B", "Legacy loop"],
    code: "",
    correctAnswer: "for (auto x : container)",
  },
  {
    category: "STL Algorithms",
    question: "What does std::algorithm header contain?",
    options: ["Data structures", "Common algorithms", "Memory management", "String utilities"],
    code: "",
    correctAnswer: "Common algorithms",
  },
  {
    category: "Fundamentals",
    question: "How do you define a constant in C++?",
    options: ["#define PI 3.14", "const float PI = 3.14;", "Both A and B", "constexpr float PI = 3.14;"],
    code: "",
    correctAnswer: "Both A and B",
  },
  {
    category: "Fundamentals",
    question: "What is the output of 5 / 2 in C++?",
    options: ["2.5", "2", "3", "Compilation error"],
    code: "",
    correctAnswer: "2",
  },
  {
    category: "Fundamentals",
    question: "Which header should you include for input/output?",
    options: ["<input>", "<iostream>", "<io>", "<stdio>"],
    code: "",
    correctAnswer: "<iostream>",
  },
  {
    category: "Fundamentals",
    question: "What is namespace std?",
    options: ["Standard standard", "Standard library namespace", "Static definition", "Standard structure"],
    code: "",
    correctAnswer: "Standard library namespace",
  },
  {
    category: "Fundamentals",
    question: "How do you access the std namespace without std::",
    options: ["import std", "using namespace std;", "include <std>", "activate std"],
    code: "",
    correctAnswer: "using namespace std;",
  },
  {
    category: "Memory Management",
    question: "What keyword is used for dynamic memory allocation?",
    options: ["alloc", "new", "malloc", "create"],
    code: "",
    correctAnswer: "new",
  },
  {
    category: "Memory Management",
    question: "Which performs better - std::unique_ptr or std::shared_ptr?",
    options: ["std::unique_ptr", "std::shared_ptr", "Same performance", "Depends on compiler"],
    code: "",
    correctAnswer: "std::unique_ptr",
  },
  {
    category: "Memory Management",
    question: "What is RAII?",
    options: ["Resource Acquisition Is Implementation", "Resource Allocation In Initialization", "Resource Access Is Isolated", "Resource As Is Immediately"],
    code: "",
    correctAnswer: "Resource Allocation In Initialization",
  },
  {
    category: "OOP",
    question: "What is the difference between struct and class in C++?",
    options: ["No difference", "struct is for data, class is for functions", "Different default access specifiers", "struct is deprecated"],
    code: "",
    correctAnswer: "Different default access specifiers",
  },
  {
    category: "OOP",
    question: "Can you override a private method?",
    options: ["Yes", "No", "Only in derived classes", "Only with templates"],
    code: "",
    correctAnswer: "No",
  },
];
